import math

import pygame


BASE_W = 650
BASE_H = 650

WINDOW_W = 650
WINDOW_H = 650

HEADER_H_BASE = 70
TILE_SIZE_BASE = 34
GRID_COLS = 18
GRID_ROWS = 16
START_SNAKE_SEGMENTS = 4

TICK_RATE = 125
FPS = 60
DEATH_FACE_COLLISION_INTRO_MS = 300
DEATH_FACE_RECOIL_MS = 75
DEATH_OVERLAY_REVEAL_MS = 960
DEATH_SCREEN_DELAY_MS = max(
    0,
    DEATH_OVERLAY_REVEAL_MS - (DEATH_FACE_COLLISION_INTRO_MS + DEATH_FACE_RECOIL_MS),
)
BORDER_CONTACT_INSET_TILES = 0.88
COLLISION_BACKUP_TILES = 1.0
COLLISION_PATH_EXTRA_CELLS = int(math.ceil(COLLISION_BACKUP_TILES)) + 2
COLLISION_TAIL_INSET_TILES = 0.30
COLLISION_EFFECT_SCALE = 1.5
COLLISION_EFFECT_FRAME_COUNT = 21
COLLISION_EFFECT_SPEED_MULT = 2.5
COLLISION_EFFECT_ANCHOR_FWD = -1.2
COLLISION_EFFECT_EXTRA_ROT_DEG = 180
COLLISION_SHAKE_DURATION_MS = 520
COLLISION_SHAKE_AMPLITUDE_TILES = 0.22
COLLISION_SHAKE_X_CYCLES = 9.0
COLLISION_SHAKE_Y_CYCLES = 13.0
BOARD_BORDER_STROKE_BASE = 2
STARTER_CARD_BASE_W = 310
STARTER_CARD_BUTTON_GAP = 12
STARTER_CARD_STAT_LEFT_X = 0.29
STARTER_CARD_STAT_RIGHT_X = 0.71
STARTER_CARD_STAT_Y = 0.44
STARTER_CARD_DIM_ALPHA = 160
STARTER_CARD_Y_OFFSET = 66
WAITING_CUE_ICON_BASE_W = 92
WAITING_CUE_BOX_PAD = 14
WAITING_CUE_BOX_ALPHA = 150
WAITING_CUE_BOX_RADIUS = 16
WAITING_CUE_CENTER_Y_RATIO = 0.24
DEATH_FACE_FRAME_COUNT = 36
DEATH_FACE_SCALE = 1.08
DEATH_FACE_SEPARATOR_W = 1
DEATH_FACE_RECOIL_START_FRAME = 6
DEATH_FACE_TWITCH_START_FRAME = 17
DEATH_FACE_TWITCH_FRAME_MS = 75
DEATH_FACE_PRE_TWITCH_ANCHOR = -0.05
DEATH_FACE_TWITCH_ANCHOR = -0.27
DEATH_FACE_ANCHOR_BACK_SHIFT = -0.03
DEATH_FACE_TWITCH_BLEND_FRAMES = 17
DEATH_FACE_FRAME_LIFT = -0.10
DEATH_FACE_UP_COLLISION_Y_NUDGE_TILES = 0.10
AUDIO_MIXER_FREQUENCY = 44100
AUDIO_MIXER_SIZE = -16
AUDIO_MIXER_CHANNELS = 2
AUDIO_MIXER_BUFFER = 512
TURN_SFX_STACK_CHANNELS = 4
COLLISION_SFX_CHANNEL_INDEX = TURN_SFX_STACK_CHANNELS
AUDIO_RESERVED_CHANNELS = TURN_SFX_STACK_CHANNELS + 1
TURN_SFX_VOLUME = 0.35
EAT_SFX_VOLUME = 0.45
COLLISION_SFX_VOLUME = 0.75

HEADER_COLOUR = (78, 112, 50)
PANEL_COLOUR = (87, 138, 52)
TILE_LIGHT = (154, 202, 60)
TILE_DARK = (140, 185, 50)
SNAKE_HEAD_COL = (78, 126, 240)
SNAKE_TAIL_DARK_MAX = (18, 38, 110)
APPLE_DARKEN_STEP = 0.050
MOUTH_TRIGGER_RADIUS_TILES = 2
MOUTH_OPEN_CLOSE_FRAMES = 10
MOUTH_CLOSE_DELAY_SEC = 0.15
MOUTH_ANCHOR_FWD = 0.45
MOUTH_ANCHOR_SIDE = 0.00
MOUTH_SCALE = 1.20
TONGUE_RATTLE_MIN_SEC = 0
TONGUE_RATTLE_MAX_SEC = 10.0
TONGUE_RATTLE_MODE_SEC = 5.0
TONGUE_FRAME_SEC = 0.025
TONGUE_SCALE = 1.10
TONGUE_ANCHOR_FWD = 0.45
TONGUE_ANCHOR_SIDE = 0.00
TONGUE_SHADOW_SCALE = 0.88
TONGUE_SHADOW_ALPHA = 40
TONGUE_SHADOW_YOFF_FACTOR = 0.16
TONGUE_BASE_OFFSET = 0.42
EYE_SCALE = 1.15
EYE_CENTER_FWD = -0.45
EYE_CENTER_SIDE = 0.00
EYE_SEPARATION = 0.32
EYE_SHADOW_SCALE = 0.8
SNAKE_SHADOW_ALPHA = 40
SNAKE_SHADOW_YOFF_FACTOR = 0.42
SNAKE_SHADOW_RADIUS_FACTOR = 0.96
EYE_BLINK_MIN_SEC = max(1.0, TONGUE_RATTLE_MIN_SEC * 0.5)
EYE_BLINK_MAX_SEC = max(EYE_BLINK_MIN_SEC, TONGUE_RATTLE_MAX_SEC * 0.5)
EYE_BLINK_MODE_SEC = max(EYE_BLINK_MIN_SEC, TONGUE_RATTLE_MODE_SEC * 0.5)
EYE_BLINK_FRAME_SEC = 0.035
BULGE_START_SCALE = 1.75
BULGE_MIN_END_SCALE = 1.00
BULGE_SHADOW_ALPHA = 34
BULGE_END_HIDE_T = 0.96
BULGE_SPAWN_DELAY_FRAMES = 4
BULGE_TRAVEL_SEG_PER_TICK = 0.70
BULGE_FADE_SEGMENTS_CAP = 25
BULGE_MIN_VISIBLE_SCALE = 1.0
BULGE_SAMPLE_STEP_FACTOR = 0.40
GROWTH_REVEAL_TILES_PER_TILE = 0.90
FACE_SHADOW_ALPHA = 38
FACE_SHADOW_YOFF_FACTOR = 0.55
MOUTH_SHADOW_SCALE = 0.95
SEGMENT_SHRINK_PER_SEG = 0.25
TAIL_MIN_RADIUS_FACTOR = 0.62
EYE_FRAME_COUNT = 9
EYE_FRAME_W = 28
EYE_SEPARATOR_W = 1

EYE_WHITE = (235, 235, 235)
EYE_PUPIL = (20, 20, 20)
EYE_RING = (95, 135, 235)
NOSE_CLR = (18, 60, 160)
SCORE_COLOUR = (255, 255, 255)

RIGHT = (1, 0)
LEFT = (-1, 0)
DOWN = (0, 1)
UP = (0, -1)

DIR_KEYS = {
    pygame.K_RIGHT: RIGHT,
    pygame.K_d: RIGHT,
    pygame.K_LEFT: LEFT,
    pygame.K_a: LEFT,
    pygame.K_DOWN: DOWN,
    pygame.K_s: DOWN,
    pygame.K_UP: UP,
    pygame.K_w: UP,
}

CROPPED_UI_CANVAS_METADATA = {
    "apple_icon": {"canvas_size": (40, 40), "offset": (8, 3)},
    "full_screen": {"canvas_size": (40, 40), "offset": (11, 10)},
    "not_full_screen": {"canvas_size": (40, 36), "offset": (6, 4)},
    "start_box": {"canvas_size": (92, 84), "offset": (23, 22)},
    "trophy": {"canvas_size": (40, 40), "offset": (8, 5)},
    "x": {"canvas_size": (40, 40), "offset": (12, 12)},
}
